// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZNcxmzpIoDYO_Yn5j69vLM0x8AN17LQg',
    appId: '1:712853589044:web:c9da196113bba6462e0e61',
    messagingSenderId: '712853589044',
    projectId: 'cloudlearn-63dc8',
    authDomain: 'cloudlearn-63dc8.firebaseapp.com',
    storageBucket: 'cloudlearn-63dc8.firebasestorage.app',
    measurementId: 'G-FZ540GXW1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMHmhzQ5QHIWLh5pPUls83NaICVdN1IoE',
    appId: '1:712853589044:android:df589b4d5cad50682e0e61',
    messagingSenderId: '712853589044',
    projectId: 'cloudlearn-63dc8',
    storageBucket: 'cloudlearn-63dc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4l9mUP6XFBleJduQEaQHLUQpu4V-fGEM',
    appId: '1:712853589044:ios:065409a7f5aa99852e0e61',
    messagingSenderId: '712853589044',
    projectId: 'cloudlearn-63dc8',
    storageBucket: 'cloudlearn-63dc8.firebasestorage.app',
    iosBundleId: 'com.example.flut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4l9mUP6XFBleJduQEaQHLUQpu4V-fGEM',
    appId: '1:712853589044:ios:065409a7f5aa99852e0e61',
    messagingSenderId: '712853589044',
    projectId: 'cloudlearn-63dc8',
    storageBucket: 'cloudlearn-63dc8.firebasestorage.app',
    iosBundleId: 'com.example.flut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZNcxmzpIoDYO_Yn5j69vLM0x8AN17LQg',
    appId: '1:712853589044:web:f93aa51455619a022e0e61',
    messagingSenderId: '712853589044',
    projectId: 'cloudlearn-63dc8',
    authDomain: 'cloudlearn-63dc8.firebaseapp.com',
    storageBucket: 'cloudlearn-63dc8.firebasestorage.app',
    measurementId: 'G-DRH2DZ6J6W',
  );
}
